### ISSUE TITLE
No videos play

### ISSUE THREAD

**Issue by yodaluca23** [Duell10111/ReactTube#23]
This is happening to all/most third-party YouTube apps. I'm pretty sure YouTube did something and broke their API but no YouTube video loads. It just shows a yellow exclamation mark (⚠️) and video doesn't load, everything else works search, and everything else but not actually playing videos.

**Comment by Duell10111** [comment]
An update could be needed for the youtube.js dependency, but as the latest version is breaking there need to be some major adaptions, espacially for the account management.

I adapted this already on my downloader-backup branch and there seems to be no issues.

I tied to apply the changes to https://github.com/Duell10111/ReactTube/tree/youtube-js-upgrade, you can try that one and check if it is working there. :)

**Comment by Duell10111** [comment]
Shouldn't be a issue anymore with current version

**Comment by yodaluca23** [comment]
Can confirm it's working :) thank u!

**Comment by Blackspell01** [comment]
Does it still work for you?

**Comment by Duell10111** [comment]
@Blackspell01 It still works for me with the latest version on the main branch, I merged today. :)

**Comment by Blackspell01** [comment]
Where can I download the unsigned ipa? For me 0.12 did not work

**Comment by yodaluca23** [comment]
> Where can I download the unsigned ipa? For me 0.12 did not work 

https://github.com/Duell10111/ReactTube/actions/runs/11421668996#artifacts
Here is the latest.

**Comment by Duell10111** [comment]
Otherwise you can try my latest 0.1.3 build.

https://github.com/Duell10111/ReactTube/actions/runs/12967209428

I will try to fix the issue that the artifacts are not mapped to the releases atm.

**Comment by Blackspell01** [comment]
Unfortunately it still doesnt play any kind of video for me :(.

**Comment by Duell10111** [comment]
On what platform are you using the App? iOS, tvOS?

**Comment by Blackspell01** [comment]
tvOS. Maybe I have to reinstall it but I cant unfortunately because my apple account has 0/10 resigns left currently

**Comment by Duell10111** [comment]
Hmm, okay what Video Resolution Type are you using http or hls?
You can change this in the settings.
You could try to use HLS.

**Comment by Blackspell01** [comment]
Ah, now it works, thanks. :)

Do you think the login capability will be repaired anytime soon?

**Comment by Duell10111** [comment]
Yes at least for TV there is a fix in work.
I added the TV endpoints to the youtubei.js library I use, but currently the PR therefore is not merged.
https://github.com/LuanRT/YouTube.js/pull/872

I have a testing branch on github where the login works again for tvOS, if you want to test yourself:
But this has to be built by yourself. :D
https://github.com/Duell10111/ReactTube/tree/dev-home-tv

**Comment by Blackspell01** [comment]
Cool, im curious. My abilities combined with chat gpt have not been enough to compile it successfully though 🥲
